# Generated by Django 4.2.3 on 2023-10-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPermissions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (("admin_access", "can use admin panel"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
