# Generated by Django 4.2.3 on 2023-10-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_orderdetail_address_remove_orderdetail_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
