# Generated by Django 4.2.3 on 2023-10-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_orderdetail_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
